set.seed(123)
n <- 100
bo <- 3
b1 <- 4
b2 <- -1.5
x <- rnorm(n, mean = 0, sd = 1)
y <- bo + b1 * x + b2 * x^2 + rnorm(n, mean = 0, sd = 3)
data <- data.frame( x = x, y = y)
model <- lm(y ~ poly(x, 3), data = data)
summary(model)
new_value <- data.frame(x = c(1, 2, 3))
predicted_value <- predict(model, new_value)
print(predicted_value)
model_arm <- arima(y, order = c(1, 0, 0))
summary(model)
acf(y)
confint(model)
pacf(y)
library(forecast)
model_rr <- auto.arima(y)
summary(model_rr)
new_v <- forecast(model_rr, h = 10)
print(new_v)
plot(new_v)
acf(residuals(model))
library(urca)
model_ur <- ur.df(y, type ="none", selectlags = "AIC")
print(model_ur)
summary(model_ur)